

USE summertides;


-- 1. Count the number of attendees from each city.
SELECT
    city,
    COUNT(*) AS total_attendees
FROM attendees
GROUP BY city;


-- 2. Count artists by genre.
SELECT
    genre,
    COUNT(*) AS number_of_artists
FROM artists
GROUP BY genre;


-- 3. Find the average ticket price for each ticket type.
SELECT
    ticket_type,
    AVG(price) AS average_price
FROM tickets
GROUP BY ticket_type;


-- 4. Calculate total ticket revenue by ticket type.
SELECT
    ticket_type,
    SUM(price) AS total_revenue
FROM tickets
GROUP BY ticket_type;


-- 5. Find the number of performances on each stage.
SELECT
    stage_id,
    COUNT(*) AS total_performances
FROM performances
GROUP BY stage_id;


-- 6. Find total sales amount generated by each vendor.
SELECT
    vendor_id,
    SUM(sale_amount) AS total_sales
FROM sales
GROUP BY vendor_id;


-- 7. Display vendors that generated more than 10000 in sales.
SELECT
    vendor_id,
    SUM(sale_amount) AS total_sales
FROM sales
GROUP BY vendor_id
HAVING SUM(sale_amount) > 10000;


-- 8. Count attendees by country.
SELECT
    country,
    COUNT(*) AS attendee_count
FROM attendees
GROUP BY country;


-- 9. Find the highest ticket price for each festival day.
SELECT
    festival_day,
    MAX(price) AS highest_ticket_price
FROM tickets
GROUP BY festival_day;


-- 10. Find the lowest ticket price for each festival day.
SELECT
    festival_day,
    MIN(price) AS lowest_ticket_price
FROM tickets
GROUP BY festival_day;