-- 1. Count the number of attendees with phone numbers vs without (Fixes missing city column)
SELECT 
    CASE WHEN phone_number IS NULL THEN 'No Phone' ELSE 'Has Phone' END AS phone_status,
    COUNT(*) AS total_attendees
FROM attendees
GROUP BY phone_status;

-- 2. Count artists by genre.
SELECT
    genre,
    COUNT(*) AS number_of_artists
FROM artists
GROUP BY genre;

-- 3. Find the average ticket price for each ticket type.
SELECT
    ticket_type,
    AVG(price) AS average_price
FROM tickets
GROUP BY ticket_type;

-- 4. Calculate total ticket revenue by ticket type.
SELECT
    ticket_type,
    SUM(price) AS total_revenue
FROM tickets
GROUP BY ticket_type;

-- 5. Find the number of performances on each stage.
SELECT
    stage_id,
    COUNT(*) AS total_performances
FROM performances
GROUP BY stage_id;

-- 6. QA FIX: Find total sales amount generated by each vendor (Changed sale_amount to amount)
SELECT
    vendor_id,
    SUM(amount) AS total_sales
FROM sales
GROUP BY vendor_id;

-- 7. QA FIX: Display vendors that generated more than 10000 in sales (Changed sale_amount to amount)
SELECT
    vendor_id,
    SUM(amount) AS total_sales
FROM sales
GROUP BY vendor_id
HAVING SUM(amount) > 10000;

-- 8. Count tickets sold by ticket type (Fixes missing country column)
SELECT
    ticket_type,
    COUNT(*) AS ticket_count
FROM tickets
GROUP BY ticket_type;

-- 9. Find the highest ticket price for each ticket type (Fixes missing festival_day column)
SELECT
    ticket_type,
    MAX(price) AS highest_ticket_price
FROM tickets
GROUP BY ticket_type;

-- 10. Find the lowest ticket price for each ticket type (Fixes missing festival_day column)
SELECT
    ticket_type,
    MIN(price) AS lowest_ticket_price
FROM tickets
GROUP BY ticket_type;