-- Counts performances hosted by every stage.
SELECT s.stage_name, COUNT(p.performance_id) AS performance_count
FROM stages AS s
LEFT JOIN performances AS p ON p.stage_id = s.stage_id
GROUP BY s.stage_id, s.stage_name
ORDER BY performance_count DESC, s.stage_name;

-- Calculates total vendor revenue and transaction volume by vendor.
SELECT v.vendor_name,
       SUM(vs.sales_amount) AS total_sales,
       SUM(vs.transactions) AS total_transactions
FROM vendors AS v
JOIN vendor_sales AS vs ON vs.vendor_id = v.vendor_id
GROUP BY v.vendor_id, v.vendor_name
ORDER BY total_sales DESC;

-- Calculates ticket revenue generated by each ticket type.
SELECT tt.ticket_name,
       SUM(tp.quantity) AS tickets_sold,
       SUM(tp.quantity * tt.price) AS ticket_revenue
FROM ticket_types AS tt
LEFT JOIN ticket_purchases AS tp ON tp.ticket_type_id = tt.ticket_type_id
GROUP BY tt.ticket_type_id, tt.ticket_name
ORDER BY ticket_revenue IS NULL, ticket_revenue DESC;
